# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/innovian/innovian-podspec.git'

target 'Palette' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'AFNetworking', '~> 3.0'
	pod ‘iOS-Codebase’
	pod 'HyperWindowSwitch'
  # Pods for Palette

end
